server:
  port: 9000
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /ad
  routes:
    sponsor:
      path: /sponsor/**
      serviceId: eureka-client-sponsor
      strip-prefix: false